name: Node.js CI/CD #워크프롤어 이름

on:
  push:
    branches: ["mater"] #push시 master

jobs:
  build:
    runs-on: self-hosted #로컬에 실행
    strategy:
      matrix:
        node-version: [22.x] #node버전 행렬
    steps:
    - uses: action/checkout@v4.2.2 #action 사용
    - name: Use Node.js ${{ matrix.node-version }}
      uses: action/setup-node@v4.1.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci #shell cmd
    - run: npm test
